site_name: My Gridfinity Collection
site_url: https://zergie.github.io/gridfinity-UltraLight/
repo_url: https://github.com/Zergie/gridfinity-UltraLight
theme:
  name: darkly
plugins:
  - macros
extra_css:
  - css/styles.css
extra_javascript:
  - js/highlight-column.js